[project]
name = "stx-mass-deploy"
description = "Mass deploy 30 contracts on mainnet"
requirements = []
[contracts.creative1]
path = "contracts/creative1.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative2]
path = "contracts/creative2.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative3]
path = "contracts/creative3.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative4]
path = "contracts/creative4.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative5]
path = "contracts/creative5.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative6]
path = "contracts/creative6.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative7]
path = "contracts/creative7.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative8]
path = "contracts/creative8.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative9]
path = "contracts/creative9.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative10]
path = "contracts/creative10.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative11]
path = "contracts/creative11.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative12]
path = "contracts/creative12.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative13]
path = "contracts/creative13.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative14]
path = "contracts/creative14.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative15]
path = "contracts/creative15.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative16]
path = "contracts/creative16.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative17]
path = "contracts/creative17.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative18]
path = "contracts/creative18.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative19]
path = "contracts/creative19.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative20]
path = "contracts/creative20.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative21]
path = "contracts/creative21.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative22]
path = "contracts/creative22.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative23]
path = "contracts/creative23.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative24]
path = "contracts/creative24.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative25]
path = "contracts/creative25.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative26]
path = "contracts/creative26.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative27]
path = "contracts/creative27.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative28]
path = "contracts/creative28.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative29]
path = "contracts/creative29.clar"
clarity_version = 2
epoch = 2.4
[contracts.creative30]
path = "contracts/creative30.clar"
clarity_version = 2
epoch = 2.4