[project]
name = "stx-mass-deploy"
description = "Mass deploy 100 contracts on mainnet"
requirements = []
[contracts.crt31]
path = "contracts/crt31.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt32]
path = "contracts/crt32.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt33]
path = "contracts/crt33.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt34]
path = "contracts/crt34.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt35]
path = "contracts/crt35.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt36]
path = "contracts/crt36.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt37]
path = "contracts/crt37.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt38]
path = "contracts/crt38.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt39]
path = "contracts/crt39.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt40]
path = "contracts/crt40.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt41]
path = "contracts/crt41.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt42]
path = "contracts/crt42.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt43]
path = "contracts/crt43.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt44]
path = "contracts/crt44.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt45]
path = "contracts/crt45.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt46]
path = "contracts/crt46.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt47]
path = "contracts/crt47.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt48]
path = "contracts/crt48.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt49]
path = "contracts/crt49.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt50]
path = "contracts/crt50.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt51]
path = "contracts/crt51.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt52]
path = "contracts/crt52.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt53]
path = "contracts/crt53.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt54]
path = "contracts/crt54.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt55]
path = "contracts/crt55.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt56]
path = "contracts/crt56.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt57]
path = "contracts/crt57.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt58]
path = "contracts/crt58.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt59]
path = "contracts/crt59.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt60]
path = "contracts/crt60.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt61]
path = "contracts/crt61.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt62]
path = "contracts/crt62.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt63]
path = "contracts/crt63.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt64]
path = "contracts/crt64.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt65]
path = "contracts/crt65.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt66]
path = "contracts/crt66.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt67]
path = "contracts/crt67.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt68]
path = "contracts/crt68.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt69]
path = "contracts/crt69.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt70]
path = "contracts/crt70.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt71]
path = "contracts/crt71.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt72]
path = "contracts/crt72.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt73]
path = "contracts/crt73.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt74]
path = "contracts/crt74.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt75]
path = "contracts/crt75.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt76]
path = "contracts/crt76.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt77]
path = "contracts/crt77.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt78]
path = "contracts/crt78.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt79]
path = "contracts/crt79.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt80]
path = "contracts/crt80.clar"
clarity_version = 2
epoch = 2.4
