[project]
name = "stx-mass-deploy"
description = "Mass deploy 100 contracts on mainnet"
requirements = []
[contracts.crt56]
path = "contracts/crt56.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt57]
path = "contracts/crt57.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt58]
path = "contracts/crt58.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt59]
path = "contracts/crt59.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt60]
path = "contracts/crt60.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt61]
path = "contracts/crt61.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt62]
path = "contracts/crt62.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt63]
path = "contracts/crt63.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt64]
path = "contracts/crt64.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt65]
path = "contracts/crt65.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt66]
path = "contracts/crt66.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt67]
path = "contracts/crt67.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt68]
path = "contracts/crt68.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt69]
path = "contracts/crt69.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt70]
path = "contracts/crt70.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt71]
path = "contracts/crt71.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt72]
path = "contracts/crt72.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt73]
path = "contracts/crt73.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt74]
path = "contracts/crt74.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt75]
path = "contracts/crt75.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt76]
path = "contracts/crt76.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt77]
path = "contracts/crt77.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt78]
path = "contracts/crt78.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt79]
path = "contracts/crt79.clar"
clarity_version = 2
epoch = 2.4
[contracts.crt80]
path = "contracts/crt80.clar"
clarity_version = 2
epoch = 2.4
