[network]
name = "mainnet"
stacks_node_rpc_url = "https://stacks-node-api.mainnet.stacks.co"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "primary age deliver maid sibling spice bachelor edit senior cable great cloud entire decorate nation absent fatal process goat grain erupt employ army derive"
balance = 19770
