[network]
name = "mainnet"
stacks_node_rpc_url = "https://stacks-node-api.mainnet.stacks.co"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "small flight churn dizzy urban math health satoshi scissors exchange donate city possible bicycle remove trip expire demand question air couple position start mixture"
balance = 20380
